name: Run Nightly Build Script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # This runs the workflow at midnight UTC every day

jobs:
  run-powershell:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run PowerShell script
      shell: pwsh
      run: ./nightly_build.ps1

    - name: Update nightly release
      uses: eine/tip@master
      with:
        tag: nightly
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: StableSwarmUI.exe
        
    - name: Deploy Windows release
      uses: WebFreak001/deploy-nightly@v3.1.0
      with:
        upload_url: https://uploads.github.com/repos/nirmie/StableSwarmUI-EXE/releases/157204116/assets{?name,label} # find out this value by opening https://api.github.com/repos/<owner>/<repo>/releases in your browser and copy the full "upload_url" value including the {?name,label} part
        release_id: 157204116 # same as above (id can just be taken out the upload_url, it's used to find old releases)
        asset_path: ./StableSwarmUI.exe # path to archive to upload
        asset_name: StableSwarmUI_windows-nightly-$$.exe # name to upload the release as, use $$ to insert date (YYYYMMDD) and 6 letter commit hash
        asset_content_type: application/exe # required by GitHub API
        max_releases: 7 # optional, if there are more releases than this matching the asset_name, the oldest ones are going to be deleted
